version: "3.7"

services:
  redis:
    image: redis:7.2.2-bookworm
    command: redis-server --save 60 1 --loglevel notice --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - cache:/data
    networks:
      - cache_link
    healthcheck:
        test: echo 'auth ${REDIS_PASSWORD}\nping' | redis-cli | grep PONG
        interval: 5s
        timeout: 3s
        retries: 5

  api:
    build:
      context: ../src
      dockerfile: Dockerfile
      target: development
    command: flask --app api.app run --host 0.0.0.0 --port 8000 --debug
    environment:
      SECRET_KEY: ${SECRET_KEY-secret}
      REDIS_HOST: ${REDIS_HOST-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD-password}
    ports:
      - 8000:8000
    volumes:
      - ../src:/src
    networks:
      - cache_link
    depends_on:
      redis:
        condition: service_healthy
  
  worker:
    build:
      context: ../src
      dockerfile: Dockerfile
      target: development
    command: celery -A api.app.celery_app worker --loglevel=debug --concurrency=${WORKER_CONCURRENCY-1}
    environment:
      SECRET_KEY: ${SECRET_KEY-secret}
      REDIS_HOST: ${REDIS_HOST-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD-password}
    volumes:
      - ../src:/src
    networks:
      - cache_link
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  cache:  # Redis data

networks:
  cache_link: # Redis network
    driver: bridge